package connectbox

// List of XML RPC setter function codes.
const (
	FnLogin  = "15"
	FnLogout = "16"
)

// List of XML RPC getter function codes.
const (
	FnGlobalSettings          = "1"
	FnCMSystemInfo            = "2"
	FnMultilang               = "3"
	FnStatus                  = "5"
	FnConfiguration           = "6"
	FnDownstreamTable         = "10"
	FnUpstreamTable           = "11"
	FnSignalTable             = "12"
	FnEventLogTable           = "13"
	FnFirewallLogTable        = "19"
	FnLangsetlist             = "21"
	FnFail                    = "22"
	FnLoginTimer              = "24"
	FnLANSetting              = "100"
	FnDHCPv6Info              = "103"
	FnBasicDHCP               = "105"
	FnWANSetting              = "107"
	FnIPFiltering             = "109"
	FnIPv6filtering           = "111"
	FnPortTrigger             = "113"
	FnWebFilter               = "115"
	FnIPv6WebFilter           = "117"
	FnMACFiltering            = "119"
	FnForwarding              = "121"
	FnLANUserTable            = "123"
	FnDDNS                    = "124"
	FnRemoteAccess            = "131"
	FnMTUSize                 = "134"
	FnCMState                 = "136"
	FnWiredState1             = "137"
	FnWiredState2             = "143"
	FnCMStatus                = "144"
	FnEthFlaplist             = "147"
	FnWirelessBasic1          = "300"
	FnWirelessWmm             = "302"
	FnWirelessSiteSurvey      = "305"
	FnWirelessGuestNetwork1   = "307"
	FnCMWirelessWPS1          = "309"
	FnCMWirelessAccessControl = "311"
	FnChannelMap              = "313"
	FnWirelessBasic2          = "315"
	FnWirelessGuestNetwork2   = "317"
	FnWirelessClient          = "322"
	FnCMWirelessWPS2          = "323"
	FnDefaultValue            = "324"
	FnGstRandomPassword       = "325"
	FnWIFIState               = "326"
	FnWirelessResetting       = "328"
)
